### ISSUE TITLE
API response not showing new keys

### ISSUE THREAD

**Issue by tomexx** [raffaelj/cockpit_ImageResize#3]
Hello,

I tried to use this plugin but I cannot see any change in the API response. The image variations are being created correctly. Should I setup anything else apart from config?

My config:

```
...
imageresize:
  keepOriginal: false
  customFolder: /original
  optimize: true
  prettyNames: true
  replaceAssetsManager: true
  profiles:
    preview:
      width: 320
      height: 320
      quality: 80
    preview_2x:
      width: 640
      height: 640
      quality: 80
...
```
